#!/bin/bash
#
# Forgejo Installation Script (Binary with SQLite3)
# Based on Forgejo Docs v13.0
#
# This script installs Forgejo from binary on Debian/Ubuntu systems
# using SQLite3 as the database backend.
#

set -euo pipefail

# Configuration variables - modify these as needed
FORGEJO_VERSION="${FORGEJO_VERSION:-13.0.0}"
FORGEJO_DOMAIN="${FORGEJO_DOMAIN:-localhost}"
FORGEJO_HTTP_PORT="${FORGEJO_HTTP_PORT:-3000}"
FORGEJO_USER="git"
FORGEJO_HOME="/home/${FORGEJO_USER}"
FORGEJO_WORK_DIR="/var/lib/forgejo"
FORGEJO_CONFIG_DIR="/etc/forgejo"

# Detect architecture
detect_arch() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64)  echo "amd64" ;;
        aarch64) echo "arm64" ;;
        armv7l)  echo "arm-6" ;;
        *)
            echo "Unsupported architecture: $arch" >&2
            exit 1
            ;;
    esac
}

ARCH=$(detect_arch)
FORGEJO_BINARY="forgejo-${FORGEJO_VERSION}-linux-${ARCH}"
DOWNLOAD_URL="https://codeberg.org/forgejo/forgejo/releases/download/v${FORGEJO_VERSION}/${FORGEJO_BINARY}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# Install dependencies
install_dependencies() {
    log_info "Installing dependencies (git, git-lfs, wget)..."
    apt-get update -qq
    apt-get install -y -qq git git-lfs wget
    log_info "Dependencies installed successfully"
}

# Create git user
create_git_user() {
    if id "${FORGEJO_USER}" &>/dev/null; then
        log_warn "User '${FORGEJO_USER}' already exists, skipping creation"
    else
        log_info "Creating system user '${FORGEJO_USER}'..."
        adduser --system --shell /bin/bash --gecos 'Git Version Control' \
            --group --disabled-password --home "${FORGEJO_HOME}" "${FORGEJO_USER}"
        log_info "User '${FORGEJO_USER}' created successfully"
    fi
}

# Download Forgejo binary
download_forgejo() {
    log_info "Downloading Forgejo v${FORGEJO_VERSION} for ${ARCH}..."
    
    local tmp_dir
    tmp_dir=$(mktemp -d)
    cd "$tmp_dir"
    
    wget -q --show-progress "${DOWNLOAD_URL}" -O "${FORGEJO_BINARY}"
    
    # Optional: Download and verify GPG signature
    # wget -q "${DOWNLOAD_URL}.asc" -O "${FORGEJO_BINARY}.asc"
    # gpg --verify "${FORGEJO_BINARY}.asc" "${FORGEJO_BINARY}"
    
    log_info "Installing Forgejo binary to /usr/local/bin/forgejo..."
    cp "${FORGEJO_BINARY}" /usr/local/bin/forgejo
    chmod 755 /usr/local/bin/forgejo
    
    cd -
    rm -rf "$tmp_dir"
    
    log_info "Forgejo binary installed successfully"
}

# Create required directories
create_directories() {
    log_info "Creating Forgejo directories..."
    
    # Data directory
    if [[ ! -d "${FORGEJO_WORK_DIR}" ]]; then
        mkdir -p "${FORGEJO_WORK_DIR}"
    fi
    chown "${FORGEJO_USER}:${FORGEJO_USER}" "${FORGEJO_WORK_DIR}"
    chmod 750 "${FORGEJO_WORK_DIR}"
    
    # Config directory
    if [[ ! -d "${FORGEJO_CONFIG_DIR}" ]]; then
        mkdir -p "${FORGEJO_CONFIG_DIR}"
    fi
    chown root:"${FORGEJO_USER}" "${FORGEJO_CONFIG_DIR}"
    chmod 770 "${FORGEJO_CONFIG_DIR}"
    
    # Create subdirectories for data
    mkdir -p "${FORGEJO_WORK_DIR}/data"
    mkdir -p "${FORGEJO_WORK_DIR}/log"
    mkdir -p "${FORGEJO_WORK_DIR}/custom"
    chown -R "${FORGEJO_USER}:${FORGEJO_USER}" "${FORGEJO_WORK_DIR}"
    
    log_info "Directories created successfully"
}

# Create systemd service
create_systemd_service() {
    log_info "Creating systemd service..."
    
    cat > /etc/systemd/system/forgejo.service << 'EOF'
[Unit]
Description=Forgejo - Beyond coding. We forge.
Documentation=https://forgejo.org/docs/latest/
After=network.target
#Wants=mysql.service
#After=mysql.service
#Wants=mariadb.service
#After=mariadb.service
#Wants=postgresql.service
#After=postgresql.service
#Wants=memcached.service
#After=memcached.service
#Wants=redis.service
#After=redis.service

[Service]
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/var/lib/forgejo
ExecStart=/usr/local/bin/forgejo web --config /etc/forgejo/app.ini
Restart=always
Environment=USER=git HOME=/home/git FORGEJO_WORK_DIR=/var/lib/forgejo

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    log_info "Systemd service created successfully"
}

# Create app.ini configuration for SQLite3
create_config() {
    log_info "Creating Forgejo configuration (SQLite3)..."
    
    cat > "${FORGEJO_CONFIG_DIR}/app.ini" << EOF
; Forgejo Configuration
; Generated by install script

APP_NAME = Forgejo: Beyond coding. We forge.
RUN_MODE = prod
RUN_USER = ${FORGEJO_USER}
WORK_PATH = ${FORGEJO_WORK_DIR}

[database]
DB_TYPE = sqlite3
PATH = ${FORGEJO_WORK_DIR}/data/forgejo.db
; Use WAL mode for better performance
SQLITE_JOURNAL_MODE = WAL

[repository]
ROOT = ${FORGEJO_WORK_DIR}/data/forgejo-repositories

[server]
DOMAIN = ${FORGEJO_DOMAIN}
HTTP_PORT = ${FORGEJO_HTTP_PORT}
ROOT_URL = http://${FORGEJO_DOMAIN}:${FORGEJO_HTTP_PORT}/
DISABLE_SSH = false
SSH_DOMAIN = ${FORGEJO_DOMAIN}
SSH_PORT = 22
LFS_START_SERVER = true
LFS_JWT_SECRET = $(openssl rand -base64 32 | tr -d '\n')
OFFLINE_MODE = false

[lfs]
PATH = ${FORGEJO_WORK_DIR}/data/lfs

[log]
MODE = console, file
LEVEL = info
ROOT_PATH = ${FORGEJO_WORK_DIR}/log

[security]
INSTALL_LOCK = false
SECRET_KEY = $(openssl rand -base64 32 | tr -d '\n')
INTERNAL_TOKEN = $(openssl rand -base64 64 | tr -d '\n')

[service]
DISABLE_REGISTRATION = false
REQUIRE_SIGNIN_VIEW = false
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
ENABLE_CAPTCHA = false

[cache]
ADAPTER = memory

[session]
PROVIDER = file

[picture]
AVATAR_UPLOAD_PATH = ${FORGEJO_WORK_DIR}/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = ${FORGEJO_WORK_DIR}/data/repo-avatars

[attachment]
PATH = ${FORGEJO_WORK_DIR}/data/attachments

[indexer]
ISSUE_INDEXER_PATH = ${FORGEJO_WORK_DIR}/indexers/issues.bleve
REPO_INDEXER_PATH = ${FORGEJO_WORK_DIR}/indexers/repos.bleve
EOF

    chown root:"${FORGEJO_USER}" "${FORGEJO_CONFIG_DIR}/app.ini"
    chmod 640 "${FORGEJO_CONFIG_DIR}/app.ini"
    
    log_info "Configuration created successfully"
}

# Create convenience script for CLI usage
create_cli_wrapper() {
    log_info "Creating CLI wrapper script..."
    
    cat > /usr/local/bin/forgejo-cli << EOF
#!/bin/bash
# Forgejo CLI wrapper script
sudo -u ${FORGEJO_USER} /usr/local/bin/forgejo \\
    --work-path ${FORGEJO_WORK_DIR} \\
    --config ${FORGEJO_CONFIG_DIR}/app.ini \\
    "\$@"
EOF

    chmod 755 /usr/local/bin/forgejo-cli
    log_info "CLI wrapper created at /usr/local/bin/forgejo-cli"
}

# Enable and start Forgejo service
start_service() {
    log_info "Enabling and starting Forgejo service..."
    systemctl enable forgejo.service
    systemctl start forgejo.service
    
    sleep 3
    
    if systemctl is-active --quiet forgejo.service; then
        log_info "Forgejo service started successfully"
    else
        log_error "Forgejo service failed to start"
        log_error "Check logs with: journalctl -u forgejo.service"
        exit 1
    fi
}

# Print installation summary
print_summary() {
    echo ""
    echo "=============================================="
    echo -e "${GREEN}Forgejo Installation Complete!${NC}"
    echo "=============================================="
    echo ""
    echo "Forgejo Version: ${FORGEJO_VERSION}"
    echo "Database: SQLite3"
    echo "Data Directory: ${FORGEJO_WORK_DIR}"
    echo "Config File: ${FORGEJO_CONFIG_DIR}/app.ini"
    echo ""
    echo "Access Forgejo at: http://${FORGEJO_DOMAIN}:${FORGEJO_HTTP_PORT}/"
    echo ""
    echo "Complete the initial setup through the web interface."
    echo ""
    echo "Useful commands:"
    echo "  - Check status:  systemctl status forgejo"
    echo "  - View logs:     journalctl -u forgejo -f"
    echo "  - Stop service:  systemctl stop forgejo"
    echo "  - Start service: systemctl start forgejo"
    echo "  - Use CLI:       forgejo-cli admin user list"
    echo ""
    echo "After initial web setup, secure the config:"
    echo "  sudo chmod 750 ${FORGEJO_CONFIG_DIR}"
    echo "  sudo chmod 640 ${FORGEJO_CONFIG_DIR}/app.ini"
    echo ""
}

# Main installation function
main() {
    echo ""
    echo "=============================================="
    echo "  Forgejo Binary Installation Script"
    echo "  Database: SQLite3"
    echo "=============================================="
    echo ""
    
    check_root
    install_dependencies
    create_git_user
    download_forgejo
    create_directories
    create_systemd_service
    create_config
    create_cli_wrapper
    start_service
    print_summary

    sudo chown git:git /etc/forgejo/app.ini
    sudo chmod 660 /etc/forgejo/app.ini
    sudo systemctl restart forgejo
    # sudo chown root:git /etc/forgejo /etc/forgejo/app.ini
    # sudo chmod 750 /etc/forgejo
    # sudo chmod 640 /etc/forgejo/app.ini
}

# Run main function
main "$@"